on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12.14.0
      - run: npm ci
      - run: npm run build
        env:
          FB_CONF_API_KEY: ${{ secrets.FB_CONF_API_KEY }}
          FB_CONF_AUTH_DOMAIN: ${{ secrets.FB_CONF_AUTH_DOMAIN }}
          FB_CONF_DATABASE_URL: ${{ secrets.FB_CONF_DATABASE_URL }}
          FB_CONF_PROJECT_ID: ${{ secrets.FB_CONF_PROJECT_ID }}
          FB_CONF_STORAGE_BUCKET: ${{ secrets.FB_CONF_STORAGE_BUCKET }}
          FB_CONF_MESSAGING_SENDER_ID: ${{ secrets.FB_CONF_MESSAGING_SENDER_ID }}
          FB_CONF_APP_ID: ${{ secrets.FB_CONF_APP_ID }}
          FB_CONF_MEASUREMENT_ID: ${{ secrets.FB_CONF_MEASUREMENT_ID }}
      - uses: lauravuo/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: ${{ secrets.FB_CONF_PROJECT_ID }}
